apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kennywarwick
spec:
  ports:
  - port: 3306
    targetPort: 3306 
  selector:
    app: mysql
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: kennywarwick
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kennywarwick
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7.40
        name: mysql
        envFrom:
        - secretRef:
            name: secret
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          #exec:
          #  command: ["mysql", "-u root", "-p $(MYSQL_ROOT_PASSWORD)", "SHOW DATABASES;"] 
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pv-claim

